export const PLAN = {
  name: 'Sierre-Zinal 2027',
  raceName: 'Sierre-Zinal',
  raceDate: '2027-08-07',
  raceDistanceKm: 31,
  raceElevationM: 2200,
  currentBenchmark: '7 km en 45 min',
  notes:
    'Autres entraînements: Flag football lundi et mercredi.\n\n' +
    "Règles d'ajustement:\n" +
    '- Fatigue élevée ou jambes lourdes: supprimer le vendredi et raccourcir la sortie longue de 20 à 30 %.\n' +
    '- Douleur qui modifie la foulée: arrêter la séance et ne pas compenser par une séance plus dure.\n' +
    '- Semaine très chargée au flag: garder le mardi facile et transformer le week-end en randonnée active.',
}

export const PHASES = [
  { name: 'Base', startDate: '2026-09-01', endDate: '2026-12-31', priorityDescription: 'Régularité et endurance facile', targetLongRunMinKm: 10, targetLongRunMaxKm: 14, targetWeeklyDplusMinM: 200, targetWeeklyDplusMaxM: 500, sortOrder: 1 },
  { name: 'Endurance vallonnée', startDate: '2027-01-01', endDate: '2027-03-31', priorityDescription: "Temps d'effort et sentiers", targetLongRunMinKm: 14, targetLongRunMaxKm: 18, targetWeeklyDplusMinM: 500, targetWeeklyDplusMaxM: 900, sortOrder: 2 },
  { name: 'Montée et résistance', startDate: '2027-04-01', endDate: '2027-05-31', priorityDescription: 'Côtes longues et renforcement', targetLongRunMinKm: 16, targetLongRunMaxKm: 22, targetWeeklyDplusMinM: 800, targetWeeklyDplusMaxM: 1400, sortOrder: 3 },
  { name: 'Spécifique trail', startDate: '2027-06-01', endDate: '2027-07-15', priorityDescription: 'Longues montées et descentes', targetLongRunMinKm: 20, targetLongRunMaxKm: 26, targetWeeklyDplusMinM: 1200, targetWeeklyDplusMaxM: 1800, sortOrder: 4 },
  { name: 'Affûtage', startDate: '2027-07-16', endDate: '2027-08-06', priorityDescription: 'Réduire le volume, garder du rythme', targetLongRunMinKm: 10, targetLongRunMaxKm: 16, targetWeeklyDplusMinM: 300, targetWeeklyDplusMaxM: 700, sortOrder: 5 },
]

export type RawSession = [
  date: string,
  activityType: 'flag_football' | 'running',
  sessionName: string,
  priority: 'fixed' | 'essential' | 'optional',
  targetDurationMin: number | null,
  targetDistanceKm: number | null,
  targetDplusM: number | null,
  intensity: string,
  instructions: string,
]

export const RAW_SESSIONS: RawSession[] = [
  ['2026-09-14', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-09-15', 'running', 'Footing facile', 'essential', 45, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-09-16', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-09-18', 'running', 'Footing très facile', 'optional', 35, null, null, 'Facile', 'Terrain plat'],
  ['2026-09-20', 'running', 'Sortie longue / trail', 'essential', null, 8, 150, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-09-21', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-09-22', 'running', 'Footing facile', 'essential', 45, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-09-23', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-09-25', 'running', 'Côtes courtes', 'optional', 40, null, null, 'Modéré', '6 × 45 s en côte, récupération en descente'],
  ['2026-09-27', 'running', 'Sortie longue / trail', 'essential', null, 9, 200, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-09-28', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-09-29', 'running', 'Footing facile', 'essential', 45, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-09-30', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-10-02', 'running', 'Repos ou mobilité', 'optional', null, null, null, 'Récupération', 'Option à supprimer en priorité'],
  ['2026-10-04', 'running', 'Sortie longue / trail', 'essential', null, 8, 150, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-10-05', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-10-06', 'running', 'Footing facile', 'essential', 50, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-10-07', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-10-09', 'running', 'Footing vallonné', 'optional', 40, null, null, 'Facile', 'Rester en aisance respiratoire'],
  ['2026-10-11', 'running', 'Sortie longue / trail', 'essential', null, 10, 250, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-10-12', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-10-13', 'running', 'Footing facile', 'essential', 50, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-10-14', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-10-16', 'running', 'Côtes courtes', 'optional', 40, null, null, 'Modéré', '8 × 45 s en côte'],
  ['2026-10-18', 'running', 'Sortie longue / trail', 'essential', null, 10, 300, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-10-19', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-10-20', 'running', 'Footing facile', 'essential', 45, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-10-21', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-10-23', 'running', 'Repos ou mobilité', 'optional', null, null, null, 'Récupération', 'Semaine allégée'],
  ['2026-10-25', 'running', 'Sortie longue / trail', 'essential', null, 8, 180, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-10-26', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-10-27', 'running', 'Footing facile', 'essential', 50, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-10-28', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-10-30', 'running', 'Footing vallonné', 'optional', 45, null, null, 'Facile', 'Sans chercher la vitesse'],
  ['2026-11-01', 'running', 'Sortie longue / trail', 'essential', null, 11, 350, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-11-02', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-11-03', 'running', 'Footing facile', 'essential', 50, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-11-04', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-11-06', 'running', 'Côtes', 'optional', 45, null, null, 'Modéré', '6 × 60 s en côte'],
  ['2026-11-08', 'running', 'Sortie longue / trail', 'essential', null, 12, 400, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-11-09', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-11-10', 'running', 'Footing facile', 'essential', 45, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-11-11', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-11-13', 'running', 'Repos ou mobilité', 'optional', null, null, null, 'Récupération', 'Semaine allégée'],
  ['2026-11-15', 'running', 'Sortie longue / trail', 'essential', null, 9, 220, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-11-16', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-11-17', 'running', 'Footing facile', 'essential', 55, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-11-18', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-11-20', 'running', 'Footing vallonné', 'optional', 45, null, null, 'Facile', 'Souple et relâché'],
  ['2026-11-22', 'running', 'Sortie longue / trail', 'essential', null, 12, 450, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-11-23', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-11-24', 'running', 'Footing facile', 'essential', 55, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-11-25', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-11-27', 'running', 'Côtes', 'optional', 45, null, null, 'Modéré', '8 × 60 s en côte'],
  ['2026-11-29', 'running', 'Sortie longue / trail', 'essential', null, 13, 500, 'Facile', 'Marcher dans les montées si nécessaire'],
  ['2026-11-30', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Échauffement complet'],
  ['2026-12-01', 'running', 'Footing facile', 'essential', 45, null, null, 'Facile', 'Allure conversationnelle'],
  ['2026-12-02', 'flag_football', 'Entraînement habituel', 'fixed', null, null, null, 'Intense', 'Hydratation et récupération après séance'],
  ['2026-12-04', 'running', 'Repos ou mobilité', 'optional', null, null, null, 'Récupération', 'Semaine allégée'],
  ['2026-12-06', 'running', 'Sortie longue / trail', 'essential', null, 10, 250, 'Facile', 'Marcher dans les montées si nécessaire'],
]
